/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.jmongard.git-semver-plugin") version "0.12.2"
}

val ver = semver.version;

allprojects {
    version = ver
}
