/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Git.SemVersioning.Gradle.Actions.Example.app

import Git.SemVersioning.Gradle.Actions.Example.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
