name: Create release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.printVersionStep.outputs.version }}
      changeLog: ${{ steps.printChangeLogStep.outputs.changeLog }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlew-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-

      - name: Retrieve current version number before release
        run: ./gradlew printVersion

      - name: Update release
        run: |
          ./gradlew releaseVersion --no-commit
          echo "version=$(./gradlew -q printVersion)" >> $GITHUB_OUTPUT

      - name: Push changes
        run: |
          git push origin --tags

      - name: Create GitHub release
        id: printChangeLogStep
        run: |
           ./gradlew -q printChangeLog | gh release create -d ${{ steps.printVersionStep.outputs.version }} -F -
