name: Create release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Retrieve current version number
        run: ./gradlew printVersion

      - name: Update release
        run: |
          ./gradlew releaseVersion --no-commit

      - name: Push changes
        run: |
          git push origin --tags

      - name: Retrieve updated version number
        run: ./gradlew printVersion

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Retrieve current version number to publish
        run: |
          ./gradlew printVersion
